Label fixes!

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -8,6 +8,8 @@ RUN npm install
 
 COPY . .
 
+RUN echo "=== .env.development at build time ===" && cat .env.development || echo "FILE NOT FOUND"
+
 ARG VITE_MODE=production
 
 RUN npm run build -- --mode ${VITE_MODE}
